<?xml version="1.0" encoding="UTF-8"?>
  <project xmlns="http://maven.apache.org/POM/4.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                               https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>cucumber-Java</groupId>
    <artifactId>cucumber-Java</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <maven.compiler.source>17</maven.compiler.source>
      <maven.compiler.target>17</maven.compiler.target>
      <cucumber.version>7.14.0</cucumber.version>
      <testng.version>7.10.2</testng.version>
      <testng.suite>src/test/resources/testng.xml</testng.suite>
    </properties>

    <dependencies>
      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>${cucumber.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-junit</artifactId>
        <version>${cucumber.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-testng</artifactId>
        <version>${cucumber.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>${testng.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-cucumber7-jvm</artifactId>
        <version>2.32.0</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-java-commons</artifactId>
        <version>2.32.0</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.13.2</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>4.33.0</version>
      </dependency>

      <dependency>
          <groupId>io.github.bonigarcia</groupId>
          <artifactId>webdrivermanager</artifactId>
          <version>5.6.2</version>
          <scope>test</scope>
      </dependency>

      <dependency>
          <groupId>io.cucumber</groupId>
          <artifactId>cucumber-picocontainer</artifactId>
          <version>${cucumber.version}</version>
          <scope>test</scope>
      </dependency>
    </dependencies>

    <build>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.2.2</version>
          <configuration>
            <includes>
              <include>**/TestRunner.java</include>
            </includes>
            <properties>
              <property>
                <name>allure.results.directory</name>
                <value>${project.build.directory}/allure-results</value>
              </property>
            </properties>
          </configuration>
        </plugin>
        <plugin>
          <groupId>io.qameta.allure</groupId>
          <artifactId>allure-maven</artifactId>
          <version>2.15.2</version>
          <configuration>
            <reportVersion>2.32.0</reportVersion>
          </configuration>
        </plugin>
        <plugin>
          <groupId>net.masterthought</groupId>
          <artifactId>maven-cucumber-reporting</artifactId>
          <version>5.7.0</version>
          <executions>
            <execution>
              <id>execution</id>
              <phase>post-integration-test</phase>
              <goals>
                <goal>generate</goal>
              </goals>
              <configuration>
                <projectName>cucumber-Java</projectName>
                <outputDirectory>${project.build.directory}/cucumber-report-html</outputDirectory>
                <jsonFiles>
                  <param>${project.build.directory}/cucumber.json</param>
                </jsonFiles>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </build>

    <profiles>
      <profile>
        <id>testng</id>
        <build>
          <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-surefire-plugin</artifactId>
              <configuration>
                <suiteXmlFiles>
                  <suiteXmlFile>${testng.suite}</suiteXmlFile>
                </suiteXmlFiles>
              </configuration>
            </plugin>
          </plugins>
        </build>
      </profile>
    </profiles>
  </project>